DISTANCE_THRESHOLD_MARKER_0 = 50  # for automatic charging
DISTANCE_THRESHOLD_MARKER_10 = 50 
DISTANCE_THRESHOLD_MARKER_11 = 10 

DISTANCE_POINT_P = 60 # (cm)
DISTANCE_POINT_MARKER = 50
DISTANCE_MARKER7 = 10

X_THRESHOLD = 10
X_THRESHOLD_FAR = 30

# Pause time for stopping briefly after completing the moving
PAUSE_TIME = 0.1
REST_TIME  = 1.0
RETRIES_TIME = 3.5
